name: Cross-Platform Build
on: [push]

jobs:
  # --- СБОРКА WINDOWS ---
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          arch: 'win64_msvc2019_64'
      
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          
      - name: Package Windows
        run: |
          # Собираем все DLL в папку с EXE
          windeployqt --qmldir . build/Release/appkursach.exe
          
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Visualizer-Windows
          path: build/Release/

  # --- СБОРКА ANDROID ---
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          target: 'android'
          arch: 'android_arm64_v8a'
          
      - name: Build APK
        run: |
          cmake -B build -DQT_ANDROID_BUILD_ALL_ABIS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target apk
          
      - name: Upload Android
        uses: actions/upload-artifact@v4
        with:
          name: Visualizer-Android
          path: build/android-build/*.apk
